name: Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.husky'
      - '.vscode'
      - '**.md'
      - 'scripts/**'
      - 'packages/react/examples/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.husky'
      - '.vscode'
      - '**.md'
      - 'scripts/**'
      - 'packages/react/examples/**'

jobs:
  main-test:
    name: Playground E2E test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.9.5
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install playwright browsers
        run: npx playwright install chromium

      - name: Run playwright tests
        run: pnpm test -- --forbid-only

      - name: Upload test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results-main
          path: ./test-results
          if-no-files-found: ignore

  store-test:
    name: Store unit test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.9.5
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run unit tests
        run: pnpm test:unit
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@v1
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          path: .master

      - uses: pnpm/action-setup@v2
        with:
          version: 7.9.5
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies(current)
        run: pnpm install --frozen-lockfile
      - name: Install dependencies(master)
        run: pnpm install --frozen-lockfile
        working-directory: .master

      - name: Run Benchmark in current
        run: CHROMIUM_BIN=$(which chrome) pnpm run bench
        working-directory: benchmark
      - name: Run Benchmark in master
        run: CHROMIUM_BIN=$(which chrome) pnpm run bench
        # remove this once master branch have benchmark suite
        continue-on-error: true
        working-directory: .master/benchmark
